name: dynamics-modeling
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # Current requirement for ros-roslz4
  - matplotlib
  - scikit-learn
  - tqdm
  - pyyaml
  - pip
  - pip:
    - --extra-index-url https://rospypi.github.io/simple/
    - -e .
    # Tensorboard
    - tensorboard
    - torch-tb-profiler
